// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function parse(p) {
  return p._0;
}

function $$return(a) {
  return /* Parser */{
          _0: (function (cs) {
              return [[
                        a,
                        cs
                      ]];
            })
        };
}

function then(p, f) {
  return /* Parser */{
          _0: (function (cs) {
              return Curry._1(p._0, cs).flatMap(function (param) {
                          return Curry._1(Curry._1(f, param[0])._0, param[1]);
                        });
            })
        };
}

var token = /* Parser */{
  _0: (function (cs) {
      if (cs === "") {
        return [];
      } else {
        return [[
                  cs[0],
                  cs.slice(1)
                ]];
      }
    })
};

export {
  parse ,
  $$return ,
  then ,
  token ,
}
/* No side effect */
